### ISSUE TITLE
Error in CUB dataloader setup

### ISSUE THREAD

**Issue by zimmermax98** [M-Nauta/PIPNet#1]
Hey,

I'm trying to train a PIPNet on CUB following the `README.md`. I prepared the CUB dataset directory using the code from ProtoTree, which resulted in a `dataset` directory (inside the CUB root directory), which then contains the 4 directories:
- `test_crop`
- `test_full`
- `train_corners`
- `train_crop`

When running `main.py`, I get an error on line 161 in `data.py`:

> FileNotFoundError: [Errno 2] No such file or directory: '/fastdata/MT_ExplSeg/datasets/CUB_200_2011/dataset/train'

This is because in line 21 of `data.py` we define the 3rd argument of `get_birds` as `'./data/CUB_200_2011/dataset/train'`

**My Question:** Am I to rename the directory `train_corners` to `train`, or did I miss a step here?

Thanks in advance!

**Comment by M-Nauta** [comment]
Hi, we used the normal CUB training dataset. I have created and updated the [preprocess file](https://github.com/M-Nauta/PIPNet/blob/main/util/preprocess_cub.py) and refer to that in the README. Thanks for pointing it out!
