### ISSUE TITLE
Resnet50 Model

### ISSUE THREAD

**Issue by ThomasNorr** [M-Nauta/PIPNet#4]
Hello and thanks for your fascinating work,

Would you mind uploading a resnet50 model (or even better one for Cars and one for CUB)  or/and providing the arguments needed to reproduce the results on that architecture? Or are resnet50 parameters equal, except for the mentioned differences in the paper?

Greetings

**Comment by wudemoai** [comment]
Hello, did you repeat this article? I set the training hyperparameters on the CUB200 data set according to the author's document, but I encountered some problems and did not get the corresponding weights.

**Comment by ThomasNorr** [comment]
ya, I got  roughly the same.

**Comment by M-Nauta** [comment]
Hi all, thanks for your interest in PIP-Net! Sorry that it took so long but the trained checkpoints are now uploaded and added to the README, allowing to reproduce results of the paper.
